import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection'
import AboutUs from '../components/AboutUs'
import Client from '../components/Client'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dream Careers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Navbar/>
      <HeroSection/>
      <AboutUs/>
      <Client/>
    </div>
  )
}
